@startuml diagrama_casos_de_uso
left to right direction

actor "Usuário" as usuario
actor "Criador" as criador
actor "Respondente" as respondente

usuario --|> criador
usuario --|> respondente

usecase "Criar questionário" as criar_questionario
usecase "Exibir questionários" as exibir_questionarios
usecase "Editar questionário" as editar_questionario
usecase "Apagar questionário" as apagar_questionario
usecase "Criar item" as criar_item
usecase "Editar item" as editar_item
usecase "Remover item" as remover_item
usecase "Responder questionário" as responder_questionario
usecase "Responder item" as responder_item
usecase "Editar resposta" as editar_resposta
usecase "Remover resposta" as remover_resposta
usecase "Exibir resultado" as exibir_resultado

criador -- criar_questionario
criador -- exibir_questionarios
respondente -- exibir_questionarios

criar_questionario .> criar_item : <<include>>
editar_questionario <. criar_item : <<extend>>
editar_questionario <. editar_item : <<extend>>
editar_questionario <. remover_item : <<extend>>

exibir_questionarios <. editar_questionario : <<extend>>
exibir_questionarios <. exibir_resultado : <<extend>>
exibir_questionarios <. apagar_questionario : <<extend>>
exibir_questionarios <. responder_questionario : <<extend>>
responder_questionario .> responder_item : <<include>>
responder_item <. editar_resposta : <<extend>>
responder_item <. remover_resposta : <<extend>>
@enduml 